esphome:
  name: esp-nhabep
  friendly_name: ESP_NHABEP

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "DtsfTpJd0Xk9UoNnEvxUz0ye9T9+tfBNTVJQ4ALXfmI="

ota:
  - platform: esphome
    password: "5c584a6249d83dcb8765086f1309a3e8"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Nhabep Fallback Hotspot"
    password: "l2oK1af20g2s"

captive_portal:

globals:
  - id: servo_state
    type: bool
    restore_value: yes
    initial_value: 'false'

servo:
  - id: servo_nhabep
    output: pwm_output
    min_level: 2.5%
    max_level: 12.5%

output:
  - platform: ledc
    id: pwm_output
    pin: GPIO23
    frequency: 50 Hz

switch:
  - platform: gpio
    pin: 
      number: GPIO25
      inverted: False
    name: "Light Bulb"
  
  - platform: gpio
    pin: 
      number: GPIO26
      inverted: False
    name: "Fan"
    id: exhaust_fan
    
  - platform: template
    name: "Cửa sổ"
    id: cua_so
    optimistic: False   # Bắt buộc để dashboard hiển thị trạng thái thật
    icon: "mdi:window-open"
    
    lambda: |-
      return id(servo_state);

    turn_on_action:
      - logger.log: "Mở cửa sổ (SG90 xoay 180°)"
      - servo.write:
          id: servo_nhabep
          level: 1.0
      - lambda: 'id(servo_state) = true;'

    turn_off_action:
      - logger.log: "Đóng cửa sổ (SG90 về 0°)"
      - servo.write:
          id: servo_nhabep
          level: 0.0
      - lambda: 'id(servo_state) = false;'

one_wire:
  - platform: gpio
    pin: GPIO4

sensor:
  - platform: adc
    pin: GPIO34
    name: "Gas Sensor"
    update_interval: 5s
    filters: 
      - multiply: 100
    unit_of_measurement: "%"  
      
  - platform: dht
    pin: GPIO32          
    model: DHT11         
    temperature:
      name: "Nhiệt độ"
      id: temp_phongkhach
    humidity:
      name: "Độ ẩm"
      id: humi_phongkhach
    update_interval: 5s

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO27
      inverted: True
    name: "IR Obstacle Sensor"
    device_class: motion
          