esphome:
  name: esp-outside
  friendly_name: ESP_OUTSIDE

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "ruB8nnNkDl78KZbxlD490/6PnWPbVSCNOgqmCnS5LrE="

ota:
  - platform: esphome
    password: "46ddc2410f511302793d2393190358db"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Outside Fallback Hotspot"
    password: "GIkkkiAwee2T"

captive_portal:

# ---------- I2C (cho LCD & BH1750, nếu có) ----------
i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true

# ----------------- SENSORS -----------------
sensor: 
  - platform: bh1750
    name: "Độ sáng ngoài trời"
    id: light_sensor
    address: 0x23
    update_interval: 15s

# ----------------- BINARY SENSORS -----------------
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO27
      mode: INPUT_PULLUP
      inverted: true
    name: "Giám sát mưa"
    id: rain_sensor
    device_class: moisture
    filters:
      - delayed_on: 500ms
      - delayed_off: 500ms

# ----------------- SWITCHES -----------------
switch:
  - platform: gpio
    pin:
      number: GPIO19
      inverted: False
    name: "Đèn chiếu sáng"